export const SET_TICKET_OFFICE_LIST = 'SET_TICKET_OFFICE_LIST'
export const CHOOSE_SEAT = 'CHOOSE_SEAT'
export const SET_TAB_ACTIVE='SET_TAB_ACTIVE'
export const RESET_CHOOSE_SEAT_LIST='RESET_CHOOSE_SEAT_LIST'