export const SET_USER_INFORMATION='SET_USER_INFORMATION'
export const SET_USERNAME_INFORMATION='SET_USERNAME_INFORMATION'
export const SET_USERS_LIST='SET_USERS_LIST'
export const SET_EDIT_USER='SET_EDIT_USER'